spring:
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: 6379
    password: ${SPRING_REDIS_PASSWORD:redis}
server:
  port: 8080
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: 6379
      password: ${SPRING_REDIS_PASSWORD:redis}
      repositories:
        enabled: false
